graph LR

subgraph Inputs
    subgraph Bronze
        bronzeMachineCasing[Bronze machine casing]
        bronzeCurvedPlate[Bronze curved plate]
        bronzeTank[Bronze tank]
    end

    subgraph Copper
        copperGear[Copper gear]
        copperRotor[Copper rotor]
    end

    subgraph Glass
        glassPane[Glass pane]
    end
end

subgraph Fluid pipe
    fluidPipe[Fluid pipe]
end

craftFluidPipe{Craft}
glassPane & copperRotor & bronzeCurvedPlate --> craftFluidPipe --> fluidPipe

subgraph Bronze pump
    bronzePump[Bronze pump]
end

craftBronzePump{Craft}
fluidPipe & copperGear & copperRotor & bronzeMachineCasing & bronzeTank --> craftBronzePump --> bronzePump