name = "Biotech"
author = "Mochi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "771735ca4d0fa1a153b7918d4b133a914871f006074ef6ce0c808dd884b7a2f8"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
