matchBlocks=betternether:blue_crying_obsidian regions_unexplored:cobalt_obsidian minecraft:crying_obsidian betternether:blue_obsidian minecraft:obsidian
method=overlay
layer=cutout
tiles=0-16
connectTiles=betternether:weeping_obsidian