! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null
clifftree:bog > null
clifftree:snowy_old_growth_taiga > null
clifftree:oasis > null
regions_unexplored:rocky_meadow > null