! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null

! ------------------
! REGIONS UNEXPLORED
! ------------------

regions_unexplored:alpha_grove > null
regions_unexplored:ancient_delta > null
! regions_unexplored:arid_mountains > null
! regions_unexplored:ashen_woodland > null
regions_unexplored:autumnal_maple_forest > null
! regions_unexplored:bamboo_forest > null
regions_unexplored:baobab_savanna > null
! regions_unexplored:barley_fields > null
regions_unexplored:bayou > null
regions_unexplored:bioshroom_caves > null
regions_unexplored:blackstone_basin > null
regions_unexplored:blackwood_taiga > null
regions_unexplored:boreal_taiga > null
regions_unexplored:chalk_cliffs > null
! regions_unexplored:clover_plains > null
regions_unexplored:cold_boreal_taiga > null
regions_unexplored:cold_deciduous_forest > null
! regions_unexplored:cold_river > null
! regions_unexplored:deciduous_forest > null
regions_unexplored:dry_bushland > null
! regions_unexplored:eucalyptus_forest > null
regions_unexplored:fen > null
regions_unexplored:flower_fields > null
regions_unexplored:frozen_pine_taiga > null
regions_unexplored:frozen_tundra > null
regions_unexplored:fungal_fen > null
regions_unexplored:glistering_meadow > null
! regions_unexplored:golden_boreal_taiga > null
! regions_unexplored:grassland > null
! regions_unexplored:grassy_beach > null
regions_unexplored:gravel_beach > null
regions_unexplored:highland_fields > null
! regions_unexplored:hyacinth_deeps > null
! regions_unexplored:icy_heights > null
regions_unexplored:infernal_holt > null
! regions_unexplored:joshua_desert > null
regions_unexplored:magnolia_woodland > null
! regions_unexplored:maple_forest > null
! regions_unexplored:marsh > null
regions_unexplored:mauve_hills > null
! regions_unexplored:mountains > null
! regions_unexplored:muddy_river > null
regions_unexplored:mycotoxic_undergrowth > null
regions_unexplored:old_growth_bayou > null
! regions_unexplored:orchard > null
! regions_unexplored:outback > null
! regions_unexplored:pine_slopes > null
regions_unexplored:pine_taiga > null
regions_unexplored:poppy_fields > null
regions_unexplored:prairie > null
regions_unexplored:prismachasm > null
regions_unexplored:pumpkin_fields > null
regions_unexplored:rainforest > null
regions_unexplored:redstone_abyss > null
regions_unexplored:redstone_caves > null
regions_unexplored:redwoods > null
regions_unexplored:rocky_meadow > null
! regions_unexplored:rocky_reef > null
! regions_unexplored:saguaro_desert > null
! regions_unexplored:scorching_caves > null
! regions_unexplored:shrubland > null
regions_unexplored:silver_birch_forest > null
regions_unexplored:sparse_rainforest > null
! regions_unexplored:sparse_redwoods > null
regions_unexplored:spires > null
regions_unexplored:steppe > null
regions_unexplored:temperate_grove > null
! regions_unexplored:towering_cliffs > null
! regions_unexplored:tropical_river > null
regions_unexplored:tropics > null
regions_unexplored:willow_forest > null

! ------------------
! NATURE SPIRIT
! ------------------

natures_spirit:aspen_forest > null
natures_spirit:golden_wilds > null
natures_spirit:maple_woodlands > null
natures_spirit:marigold_meadows > null
natures_spirit:fir_forest > null
natures_spirit:prairie > null
natures_spirit:redwood_forest > null
natures_spirit:coniferous_covert > null
! natures_spirit:alpine_clearings > null
natures_spirit:boreal_taiga > null
natures_spirit:blooming_dunes > null
! natures_spirit:lively_dunes > null
! natures_spirit:stratified_desert > null
natures_spirit:chaparral > null
natures_spirit:drylands > null
! natures_spirit:wooded_drylands > null
! natures_spirit:scorched_dunes > null
! natures_spirit:arid_savanna > null
natures_spirit:arid_highlands > null
! natures_spirit:shrubby_highlands > null
natures_spirit:woody_highlands > null
natures_spirit:blooming_highlands > null
! natures_spirit:bamboo_wetlands > null
! natures_spirit:marsh > null
natures_spirit:wisteria_forest > null
! natures_spirit:xeric_plains > null
! natures_spirit:cypress_fields > null
natures_spirit:carnation_fields > null
natures_spirit:lavender_fields > null
natures_spirit:white_cliffs > null
natures_spirit:tropical_shores > null
natures_spirit:tropical_woods > null
natures_spirit:tropical_basin > null
! natures_spirit:sugi_forest > null
! natures_spirit:blooming_sugi_forest > null
! natures_spirit:shrubland > null
natures_spirit:flowering_shrubland > null