[animation_settings]

	#Use the old animation style
	oldAnimationStyle = false

[compatibility_settings]

	#Disable Naturalist's Bug Net to use Faunify's Bug Net
	replaceNet = true

[spawning]

	#Spawn Weight - How often Weasels spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	weaselSpawnWeight = 10

	#Spawn Weight - How often Fennec Foxes spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	fennecSpawnWeight = 5

	#Spawn Weight - How often Chinchillas spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	chinchillaSpawnWeight = 15

	#Spawn Weight - How often Hedgehogs spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	hedgehogSpawnWeight = 8

	#Spawn Weight - How often Ringtail Cats spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	ringtailcatSpawnWeight = 12

	#Spawn Weight - How often Opossums spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	opossumSpawnWeight = 10

	#Spawn Weight - How often Mice spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	mouseSpawnWeight = 8

	#Spawn Weight - How often Silk Moths spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	silkmothSpawnWeight = 10

	#Spawn Weight - How often Leaf Sheep spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	leafsheepSpawnWeight = 45

	#Spawn Weight - How often Bee Flies spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	beeflySpawnWeight = 15

	#Spawn Weight - How often Beetles spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	beetleSpawnWeight = 15

	#Spawn Weight - How often Dragonflies spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	dragonflySpawnWeight = 20

	#Spawn Weight - How often Grasshoppers spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	grasshopperSpawnWeight = 15

	#Spawn Weight - How often Lacewings spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	lacewingSpawnWeight = 15

	#Spawn Weight - How often Ladybugs spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	ladybugSpawnWeight = 15

	#Spawn Weight - How often Leaf Insects spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	leafinsectSpawnWeight = 12

	#Spawn Weight - How often Mantises spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	mantisSpawnWeight = 12

	#Spawn Weight - How often Millipedes spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	millipedeSpawnWeight = 80

	#Spawn Weight - How often Roly Polies spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	rolypolySpawnWeight = 40

	#Spawn Weight - How often Stick Bugs spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	stickbugSpawnWeight = 12

	#Spawn Weight - How often Weevils spawn. [Higher number = Higher chance, 0 = Disable spawns]
	#Range: 0 ~ 500
	weevilSpawnWeight = 12

