#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jul 07 15:40:28 ICT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=Monophonic 1.1.zip
enableShaders=false
