#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 17 18:48:23 ICT 2026
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=6
shaderPack=Monophonic 1.1.zip
