#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun May 10 20:58:20 ICT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=Chocapic13_HighPerformance_Toaster.zip
enableShaders=false
