version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
tconstruct = true
fastitemframes = true
tide = true
farmersdelight = true
mutantmonsters = true
somemoreblocks = true
nears = true
blast = true
alloy_forgery = true
overweight_farming = true
faunify = true
reinfshulker = true
oceansdelight = true
betterend = true
cataclysm = true
golemoverhaul = true
star = true
friendsandfoes = true
loadmychunks = true
natures_spirit = true
earlystage = true
mysticsbiomes = true
comforts = true
aquamirae = true
ends_delight = true
fastpaintings = true
expore = true
escalated = true
bloomingnature = true
milk = true
amendments = true
mynethersdelight = true
goodending = true
ftbquests = true
immersiveores = true
snowrealmagic = true
frostiful = true
blazingbamboo = true
earth-and-water = true
modern_industrialization = true
netherchested = true
gardens_of_the_dead = true
hybrid-aquatic = true
customportalapi = true
naturalist = true
rosegoldequipment = true
cratedelight = true
minecells = true
omnihopper = true
deeperdarker = true
chipped = true
create = true
culturaldelights = true
yungscavebiomes = true
extended_drawers = true
rottencreatures = true
wildernature = true
minecraft = true
lootr = true
yaf = true
natures_delight = true
bbb = true
regions_unexplored = true
netherexp = true
molten_metals = true
blahaj = true
travelersbackpack = true
ratatouille = true
ipla = true
endermanoverhaul = true
waystones = true
creeperoverhaul = true
tradingpost = true
crittersandcompanions = true
amarite = true
moyai = true
mythicmetals = true
delightfulcreators = true
grounded = true
expandeddelight = true
illagerinvasion = true
serene_shrubbery = true
bountiful = true
hearth_and_home = true
