version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 20
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 3.4641016
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
mythicmetals = true
tconstruct = true
farmersdelight = true
bountiful = true
somemoreblocks = true
nears = true
alloy_forgery = true
overweight_farming = true
faunify = true
brewery = true
hoppergadgetry = true
star = true
golemoverhaul = true
another_furniture = true
friendsandfoes = true
twigs = true
mysticsbiomes = true
furniture = true
comforts = true
aquamirae = true
omnicrossbow = true
milk = true
amendments = true
mynethersdelight = true
handcrafted = true
herbalbrews = true
immersiveores = true
bakery = true
blazingbamboo = true
earth-and-water = true
modern_industrialization = true
hybrid-aquatic = true
naturalist = true
lilis_lucky_lures = true
cratedelight = true
supplementaries = true
omnihopper = true
suppsquared = true
chipped = true
beachparty = true
yungscavebiomes = true
farm_and_charm = true
rottencreatures = true
wildernature = true
minecraft = true
lootr = true
yaf = true
bbb = true
extractinator = true
spawn = true
netherexp = true
blahaj = true
travelersbackpack = true
nethervinery = true
endermanoverhaul = true
bosses_of_mass_destruction = true
waystones = true
creeperoverhaul = true
universal_graves = true
moyai = true
vinery = true
grounded = true
illagerinvasion = true
hearth_and_home = true
