{
  "biomeRegionWeight": 6,
  "enableExperimentalBiomeGen": false,
  "enableStrawberryFields": true,
  "enableLavenderMeadow": true,
  "enableBambooBlossomForest": true,
  "enableAutumnalGrove": true,
  "enableLushOasis": true,
  "enableLagoon": true,
  "enableTropics": true,
  "strawberryFieldsBiomeSpawns": [
    "minecraft:sunflower_plains"
  ],
  "lavenderMeadowBiomeSpawns": [
    "minecraft:meadow"
  ],
  "bambooBlossomForestBiomeSpawns": [
    "minecraft:snowy_taiga"
  ],
  "autumnalGroveBiomeSpawns": [
    "minecraft:taiga"
  ],
  "lushOasisBiomeSpawns": [
    "minecraft:desert"
  ],
  "lagoonBiomeSpawns": [
    "minecraft:beach"
  ],
  "tropicsBiomeSpawns": [
    "minecraft:jungle"
  ],
  "rainbowChickenBiomeSpawns": [
    "minecraft:plains",
    "minecraft:forest",
    "minecraft:flower_forest"
  ],
  "rainbowChickenSpawnChance": 22
}